localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=gordominossi
    - POSTGRES_PASSWORD=senhasegura(nope)
    - POSTGRES_DB=local-db

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=gordominossi
    - POSTGRES_PASSWORD=mesmasenha
    - POSTGRES_DB=test-db
